### ISSUE TITLE
When full screen mode is not enabled, there is a vertical line between the tab sidebar and the toolbar. Is this expected? 🫡

### ISSUE THREAD

**Issue by aka-phrankie** [Dinno-DEV/zen-paper-cut-theme#1]
![zen_241004_1115_36](https://github.com/user-attachments/assets/b75712a2-205e-4b11-92dd-8fccfbb15372)

Is there a way to avoid this vertical white line?

**Comment by dinnoyow** [comment]
Yes, the line is there as the separator of the sidebar. The line actually goes down below, it looks more prominent on dark pages. It does look awkward on bright pages, sadly so far I can't fix it without making it incompatible with other color/gradient themes. Sorry !
![image](https://github.com/user-attachments/assets/e78512c4-c0e6-41c0-ae9c-f2993dfe164e)

**Comment by aka-phrankie** [comment]
No problem, I can use the right sidebar in order to this plugin.

I really can't accept the intrusive feeling of intrusion into the web page without this plug-in. Thanks for the plugin. 

😊😙🥰
