### ISSUE TITLE
Not entirely pointy on v1.0.1-a.14

### ISSUE THREAD

**Issue by onthejobtraining** [Dinno-DEV/zen-paper-cut-theme#2]
![image](https://github.com/user-attachments/assets/6e88ec7f-7c7d-4010-8602-93550981adf0)
Slight distraction at the corners using Paper Cut theme on Zen 1.0.1-a.14

**Comment by dinnoyow** [comment]
It should be fixed on paper cut v1.0.3 👍 (after the theme store is updated)
